# Generated by Django 2.2.11 on 2020-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200403_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_category',
            field=models.CharField(default='General', max_length=30),
        ),
    ]
