# Generated by Django 2.2.11 on 2020-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_wish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartnew',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wish',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
