# Generated by Django 2.2.11 on 2020-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200420_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='wish/'),
        ),
    ]
